### ISSUE TITLE
scripts/simplecraterefil.sqf error line 33

### ISSUE THREAD

**Issue by onedigita** [71stSOG/71stSOG-Insurgency#3]
i lost the rpt but it was basiclyi spamming refil over and over again.  something abotu _delay being the issue

**Comment by dixon13** [comment]
script is probably not being executed with enough parameters. Try using...
<code>nul = [this,10] execVM "scripts\SimpleCrateRefill.sqf";</code>
Where '10' represents time in seconds. For more information regarding this script, read the top of the script on how to use.

**Comment by onedigita** [comment]
rgr ya i manged to fix that just need to change it to every 30 mikes
